/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as PhoneDummyNumberRouteImport } from './routes/phone-dummy.$number'
import { Route as FlowsFlowIdRouteImport } from './routes/flows.$flowId'
import { Route as ConversationsRunIdRouteImport } from './routes/conversations.$runId'
import { Route as ApiTwilioMediaStreamRouteImport } from './routes/api/twilio/media-stream'
import { Route as ApiTwilioTwimlRunIdRouteImport } from './routes/api/twilio/twiml.$runId'
import { Route as ApiTwilioStatusRunIdRouteImport } from './routes/api/twilio/status.$runId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneDummyNumberRoute = PhoneDummyNumberRouteImport.update({
  id: '/phone-dummy/$number',
  path: '/phone-dummy/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsFlowIdRoute = FlowsFlowIdRouteImport.update({
  id: '/flows/$flowId',
  path: '/flows/$flowId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRunIdRoute = ConversationsRunIdRouteImport.update({
  id: '/conversations/$runId',
  path: '/conversations/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwilioMediaStreamRoute = ApiTwilioMediaStreamRouteImport.update({
  id: '/api/twilio/media-stream',
  path: '/api/twilio/media-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwilioTwimlRunIdRoute = ApiTwilioTwimlRunIdRouteImport.update({
  id: '/api/twilio/twiml/$runId',
  path: '/api/twilio/twiml/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwilioStatusRunIdRoute = ApiTwilioStatusRunIdRouteImport.update({
  id: '/api/twilio/status/$runId',
  path: '/api/twilio/status/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/conversations/$runId': typeof ConversationsRunIdRoute
  '/flows/$flowId': typeof FlowsFlowIdRoute
  '/phone-dummy/$number': typeof PhoneDummyNumberRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/api/twilio/media-stream': typeof ApiTwilioMediaStreamRoute
  '/api/twilio/status/$runId': typeof ApiTwilioStatusRunIdRoute
  '/api/twilio/twiml/$runId': typeof ApiTwilioTwimlRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/conversations/$runId': typeof ConversationsRunIdRoute
  '/flows/$flowId': typeof FlowsFlowIdRoute
  '/phone-dummy/$number': typeof PhoneDummyNumberRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/api/twilio/media-stream': typeof ApiTwilioMediaStreamRoute
  '/api/twilio/status/$runId': typeof ApiTwilioStatusRunIdRoute
  '/api/twilio/twiml/$runId': typeof ApiTwilioTwimlRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/conversations/$runId': typeof ConversationsRunIdRoute
  '/flows/$flowId': typeof FlowsFlowIdRoute
  '/phone-dummy/$number': typeof PhoneDummyNumberRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/api/twilio/media-stream': typeof ApiTwilioMediaStreamRoute
  '/api/twilio/status/$runId': typeof ApiTwilioStatusRunIdRoute
  '/api/twilio/twiml/$runId': typeof ApiTwilioTwimlRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/conversations/$runId'
    | '/flows/$flowId'
    | '/phone-dummy/$number'
    | '/runs/$runId'
    | '/api/twilio/media-stream'
    | '/api/twilio/status/$runId'
    | '/api/twilio/twiml/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/conversations/$runId'
    | '/flows/$flowId'
    | '/phone-dummy/$number'
    | '/runs/$runId'
    | '/api/twilio/media-stream'
    | '/api/twilio/status/$runId'
    | '/api/twilio/twiml/$runId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/conversations/$runId'
    | '/flows/$flowId'
    | '/phone-dummy/$number'
    | '/runs/$runId'
    | '/api/twilio/media-stream'
    | '/api/twilio/status/$runId'
    | '/api/twilio/twiml/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ConversationsRunIdRoute: typeof ConversationsRunIdRoute
  FlowsFlowIdRoute: typeof FlowsFlowIdRoute
  PhoneDummyNumberRoute: typeof PhoneDummyNumberRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  ApiTwilioMediaStreamRoute: typeof ApiTwilioMediaStreamRoute
  ApiTwilioStatusRunIdRoute: typeof ApiTwilioStatusRunIdRoute
  ApiTwilioTwimlRunIdRoute: typeof ApiTwilioTwimlRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone-dummy/$number': {
      id: '/phone-dummy/$number'
      path: '/phone-dummy/$number'
      fullPath: '/phone-dummy/$number'
      preLoaderRoute: typeof PhoneDummyNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/$flowId': {
      id: '/flows/$flowId'
      path: '/flows/$flowId'
      fullPath: '/flows/$flowId'
      preLoaderRoute: typeof FlowsFlowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/$runId': {
      id: '/conversations/$runId'
      path: '/conversations/$runId'
      fullPath: '/conversations/$runId'
      preLoaderRoute: typeof ConversationsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio/media-stream': {
      id: '/api/twilio/media-stream'
      path: '/api/twilio/media-stream'
      fullPath: '/api/twilio/media-stream'
      preLoaderRoute: typeof ApiTwilioMediaStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio/twiml/$runId': {
      id: '/api/twilio/twiml/$runId'
      path: '/api/twilio/twiml/$runId'
      fullPath: '/api/twilio/twiml/$runId'
      preLoaderRoute: typeof ApiTwilioTwimlRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio/status/$runId': {
      id: '/api/twilio/status/$runId'
      path: '/api/twilio/status/$runId'
      fullPath: '/api/twilio/status/$runId'
      preLoaderRoute: typeof ApiTwilioStatusRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ConversationsRunIdRoute: ConversationsRunIdRoute,
  FlowsFlowIdRoute: FlowsFlowIdRoute,
  PhoneDummyNumberRoute: PhoneDummyNumberRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  ApiTwilioMediaStreamRoute: ApiTwilioMediaStreamRoute,
  ApiTwilioStatusRunIdRoute: ApiTwilioStatusRunIdRoute,
  ApiTwilioTwimlRunIdRoute: ApiTwilioTwimlRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
