/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalesPersonasRouteImport } from './routes/sales-personas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as FlowsRouteImport } from './routes/flows'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as PhoneDummyNumberRouteImport } from './routes/phone-dummy.$number'
import { Route as FlowsFlowIdRouteImport } from './routes/flows.$flowId'
import { Route as ConversationsRunIdRouteImport } from './routes/conversations.$runId'
import { Route as ApiTwilioMediaStreamRouteImport } from './routes/api/twilio/media-stream'
import { Route as ApiTwilioTwimlRunIdRouteImport } from './routes/api/twilio/twiml.$runId'
import { Route as ApiTwilioStatusRunIdRouteImport } from './routes/api/twilio/status.$runId'

const SalesPersonasRoute = SalesPersonasRouteImport.update({
  id: '/sales-personas',
  path: '/sales-personas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsRoute = FlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneDummyNumberRoute = PhoneDummyNumberRouteImport.update({
  id: '/phone-dummy/$number',
  path: '/phone-dummy/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsFlowIdRoute = FlowsFlowIdRouteImport.update({
  id: '/$flowId',
  path: '/$flowId',
  getParentRoute: () => FlowsRoute,
} as any)
const ConversationsRunIdRoute = ConversationsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => ConversationsRoute,
} as any)
const ApiTwilioMediaStreamRoute = ApiTwilioMediaStreamRouteImport.update({
  id: '/api/twilio/media-stream',
  path: '/api/twilio/media-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwilioTwimlRunIdRoute = ApiTwilioTwimlRunIdRouteImport.update({
  id: '/api/twilio/twiml/$runId',
  path: '/api/twilio/twiml/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwilioStatusRunIdRoute = ApiTwilioStatusRunIdRouteImport.update({
  id: '/api/twilio/status/$runId',
  path: '/api/twilio/status/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/company': typeof CompanyRoute
  '/conversations': typeof ConversationsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/flows': typeof FlowsRouteWithChildren
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/sales-personas': typeof SalesPersonasRoute
  '/conversations/$runId': typeof ConversationsRunIdRoute
  '/flows/$flowId': typeof FlowsFlowIdRoute
  '/phone-dummy/$number': typeof PhoneDummyNumberRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/api/twilio/media-stream': typeof ApiTwilioMediaStreamRoute
  '/api/twilio/status/$runId': typeof ApiTwilioStatusRunIdRoute
  '/api/twilio/twiml/$runId': typeof ApiTwilioTwimlRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/company': typeof CompanyRoute
  '/conversations': typeof ConversationsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/flows': typeof FlowsRouteWithChildren
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/sales-personas': typeof SalesPersonasRoute
  '/conversations/$runId': typeof ConversationsRunIdRoute
  '/flows/$flowId': typeof FlowsFlowIdRoute
  '/phone-dummy/$number': typeof PhoneDummyNumberRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/api/twilio/media-stream': typeof ApiTwilioMediaStreamRoute
  '/api/twilio/status/$runId': typeof ApiTwilioStatusRunIdRoute
  '/api/twilio/twiml/$runId': typeof ApiTwilioTwimlRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/company': typeof CompanyRoute
  '/conversations': typeof ConversationsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/flows': typeof FlowsRouteWithChildren
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/sales-personas': typeof SalesPersonasRoute
  '/conversations/$runId': typeof ConversationsRunIdRoute
  '/flows/$flowId': typeof FlowsFlowIdRoute
  '/phone-dummy/$number': typeof PhoneDummyNumberRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/api/twilio/media-stream': typeof ApiTwilioMediaStreamRoute
  '/api/twilio/status/$runId': typeof ApiTwilioStatusRunIdRoute
  '/api/twilio/twiml/$runId': typeof ApiTwilioTwimlRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns'
    | '/company'
    | '/conversations'
    | '/dashboard'
    | '/flows'
    | '/leads'
    | '/login'
    | '/sales-personas'
    | '/conversations/$runId'
    | '/flows/$flowId'
    | '/phone-dummy/$number'
    | '/runs/$runId'
    | '/api/twilio/media-stream'
    | '/api/twilio/status/$runId'
    | '/api/twilio/twiml/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaigns'
    | '/company'
    | '/conversations'
    | '/dashboard'
    | '/flows'
    | '/leads'
    | '/login'
    | '/sales-personas'
    | '/conversations/$runId'
    | '/flows/$flowId'
    | '/phone-dummy/$number'
    | '/runs/$runId'
    | '/api/twilio/media-stream'
    | '/api/twilio/status/$runId'
    | '/api/twilio/twiml/$runId'
  id:
    | '__root__'
    | '/'
    | '/campaigns'
    | '/company'
    | '/conversations'
    | '/dashboard'
    | '/flows'
    | '/leads'
    | '/login'
    | '/sales-personas'
    | '/conversations/$runId'
    | '/flows/$flowId'
    | '/phone-dummy/$number'
    | '/runs/$runId'
    | '/api/twilio/media-stream'
    | '/api/twilio/status/$runId'
    | '/api/twilio/twiml/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignsRoute: typeof CampaignsRoute
  CompanyRoute: typeof CompanyRoute
  ConversationsRoute: typeof ConversationsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FlowsRoute: typeof FlowsRouteWithChildren
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  SalesPersonasRoute: typeof SalesPersonasRoute
  PhoneDummyNumberRoute: typeof PhoneDummyNumberRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  ApiTwilioMediaStreamRoute: typeof ApiTwilioMediaStreamRoute
  ApiTwilioStatusRunIdRoute: typeof ApiTwilioStatusRunIdRoute
  ApiTwilioTwimlRunIdRoute: typeof ApiTwilioTwimlRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sales-personas': {
      id: '/sales-personas'
      path: '/sales-personas'
      fullPath: '/sales-personas'
      preLoaderRoute: typeof SalesPersonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows': {
      id: '/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof FlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone-dummy/$number': {
      id: '/phone-dummy/$number'
      path: '/phone-dummy/$number'
      fullPath: '/phone-dummy/$number'
      preLoaderRoute: typeof PhoneDummyNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/$flowId': {
      id: '/flows/$flowId'
      path: '/$flowId'
      fullPath: '/flows/$flowId'
      preLoaderRoute: typeof FlowsFlowIdRouteImport
      parentRoute: typeof FlowsRoute
    }
    '/conversations/$runId': {
      id: '/conversations/$runId'
      path: '/$runId'
      fullPath: '/conversations/$runId'
      preLoaderRoute: typeof ConversationsRunIdRouteImport
      parentRoute: typeof ConversationsRoute
    }
    '/api/twilio/media-stream': {
      id: '/api/twilio/media-stream'
      path: '/api/twilio/media-stream'
      fullPath: '/api/twilio/media-stream'
      preLoaderRoute: typeof ApiTwilioMediaStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio/twiml/$runId': {
      id: '/api/twilio/twiml/$runId'
      path: '/api/twilio/twiml/$runId'
      fullPath: '/api/twilio/twiml/$runId'
      preLoaderRoute: typeof ApiTwilioTwimlRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio/status/$runId': {
      id: '/api/twilio/status/$runId'
      path: '/api/twilio/status/$runId'
      fullPath: '/api/twilio/status/$runId'
      preLoaderRoute: typeof ApiTwilioStatusRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConversationsRouteChildren {
  ConversationsRunIdRoute: typeof ConversationsRunIdRoute
}

const ConversationsRouteChildren: ConversationsRouteChildren = {
  ConversationsRunIdRoute: ConversationsRunIdRoute,
}

const ConversationsRouteWithChildren = ConversationsRoute._addFileChildren(
  ConversationsRouteChildren,
)

interface FlowsRouteChildren {
  FlowsFlowIdRoute: typeof FlowsFlowIdRoute
}

const FlowsRouteChildren: FlowsRouteChildren = {
  FlowsFlowIdRoute: FlowsFlowIdRoute,
}

const FlowsRouteWithChildren = FlowsRoute._addFileChildren(FlowsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignsRoute: CampaignsRoute,
  CompanyRoute: CompanyRoute,
  ConversationsRoute: ConversationsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FlowsRoute: FlowsRouteWithChildren,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  SalesPersonasRoute: SalesPersonasRoute,
  PhoneDummyNumberRoute: PhoneDummyNumberRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  ApiTwilioMediaStreamRoute: ApiTwilioMediaStreamRoute,
  ApiTwilioStatusRunIdRoute: ApiTwilioStatusRunIdRoute,
  ApiTwilioTwimlRunIdRoute: ApiTwilioTwimlRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
